security:
    encoders:
        App\Entity\Security\User:
            algorithm: auto

    providers:
        users:
            entity:
                class: App\Entity\Security\User
                property: firstName

    firewalls:
        dev:
            pattern: ^/
            anonymous: true
            lazy: true
            logout: ~

            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
        main:
            pattern: ^/
            anonymous: false
            lazy: true
            logout: ~

            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

    access_control:
         #- { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/auth/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
